### ISSUE TITLE
動画

### ISSUE THREAD

**Issue by kotaroooo457** [kotaro-lab457/MyPortfolio#92]
![PF_profile_movie](https://user-images.githubusercontent.com/69884513/113230789-c0c83380-92d4-11eb-98e7-3098e9e9b22a.gif)

**Comment by kotaro-lab457** [comment]
https://user-images.githubusercontent.com/69884513/113140633-a43fe300-9263-11eb-92ae-962f5af1b6f2.mov

**Comment by kotaro-lab457** [comment]
https://s23.aconvert.com/convert/p3r68-cdx67/ywb1d-wbccu.gif

**Comment by kotaro-lab457** [comment]
https://user-images.githubusercontent.com/69884513/113227300-53fd6b00-92cd-11eb-9500-d02d2e44d609.gif

**Comment by kotaroooo457** [comment]
![PF_search_movie](https://user-images.githubusercontent.com/69884513/113231047-5368d280-92d5-11eb-8599-7d65600f935b.gif)

**Comment by kotaroooo457** [comment]
![PF_setup_movie](https://user-images.githubusercontent.com/69884513/113231190-a80c4d80-92d5-11eb-8c80-75406a5ee090.gif)

**Comment by kotaro-lab457** [comment]
<img width="413" alt="portfolio_login" src="https://user-images.githubusercontent.com/69884513/114831059-e6daf100-9e07-11eb-8b29-57813ce23b6c.png">
